[package]
name = "Rust_L1"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
flume = "0.10"
dashmap = "5.0"
num-bigint = "0.4.3"
num-traits = "0.2"
